/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CartStatus = "active" | "archived" | "checked_out";

export type FulfillmentStatus = "canceled" | "delivered" | "pending" | "processing" | "shipped";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string>;

export type OrderStatus = "failed" | "success";

export type PaymentMethodType = "cod" | "credit_card" | "paypal";

export type PaymentStatus = "canceled" | "failed" | "paid" | "pending" | "processing" | "refunded";

export type ShippingStatus = "delivered" | "in_transit" | "pending" | "returned";

export type Timestamp = ColumnType<Date, Date | string>;

export type TokenStatus = "invalid" | "revoked" | "valid";

export type TokenType = "access" | "refresh";

export interface Account {
  access_token: string | null;
  created_at: Generated<Timestamp>;
  expires_in: Int8 | null;
  id: Generated<Int8>;
  id_token: string | null;
  password: string | null;
  provider: string;
  providerAccount_id: string;
  refresh_token: string | null;
  scope: string | null;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface CardInfo {
  card_cvv: string;
  card_expiry: string;
  card_holder: string;
  card_number: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  payment_info_id: Int8;
  updated_at: Generated<Timestamp>;
}

export interface Cart {
  archived_at: Timestamp | null;
  checked_out_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  status: CartStatus;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface CartItem {
  cart_id: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  product_id: Int8;
  quantity: Numeric;
  updated_at: Generated<Timestamp>;
}

export interface Category {
  created_at: Generated<Timestamp>;
  description: string;
  icon: string;
  id: Generated<Int8>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Order {
  cart_id: Int8;
  created_at: Generated<Timestamp>;
  fulfillment_status: FulfillmentStatus;
  id: Generated<Int8>;
  status: OrderStatus | null;
  total_amount: Numeric;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface OrderItem {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  order_id: Int8;
  price_at_purchase: Numeric;
  product_id: Int8;
  quantity: Numeric;
  updated_at: Generated<Timestamp>;
}

export interface PaymentInfo {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  customer_reference_id: string | null;
  id: Generated<Int8>;
  method: PaymentMethodType;
  order_id: Int8;
  provider: string;
  status: Generated<PaymentStatus>;
  transaction_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PaypalInfo {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  payment_info_id: Int8;
  updated_at: Generated<Timestamp>;
}

export interface Product {
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<Int8>;
  name: string;
  price: Numeric;
  stock_quantity: Numeric;
  subcategory_id: Int8;
  updated_at: Generated<Timestamp>;
}

export interface ShippingInfo {
  address: string;
  city: string;
  country: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  order_id: Int8;
  postal_code: string;
  status: Generated<ShippingStatus>;
  tracking_number: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Subcategory {
  category_id: Int8;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<Int8>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Token {
  created_at: Generated<Timestamp>;
  expires_in: Int8;
  id: Generated<Int8>;
  status: TokenStatus | null;
  token: string;
  type: TokenType | null;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface User {
  created_at: Generated<Timestamp>;
  email: string | null;
  emailVerified: Timestamp | null;
  first_name: string | null;
  id: Generated<Int8>;
  image: string | null;
  last_name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  account: Account;
  card_info: CardInfo;
  cart: Cart;
  cart_item: CartItem;
  category: Category;
  order: Order;
  order_item: OrderItem;
  payment_info: PaymentInfo;
  paypal_info: PaypalInfo;
  product: Product;
  shipping_info: ShippingInfo;
  subcategory: Subcategory;
  token: Token;
  user: User;
}
