# .github/workflows/dev.yml
name: Makes CI
on: [push, pull_request]
jobs:
  Makes__all__:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://ghcr.io/fluidattacks/makes:24.09
        name: __all__
        with:
          args: sh -c "chown -R root:root /github/workspace && m . __all__"
